"""realtimeodds — Real-time betting odds SDK for Python.

Multi-bookmaker, sport-discriminated, asyncio-first. Wraps the `sb-orchestrator`
gateway WebSocket and exposes spec-compliant events to consumers.

Quickstart:
    >>> import asyncio
    >>> from realtimeodds import create_client
    >>>
    >>> async def main() -> None:
    ...     client = create_client(url="wss://api.realtimeodds.xyz", api_key="...")
    ...     client.on("sportEvent:added", lambda ev: print(ev.sport_event.id))
    ...     await client.connect()
    ...     await asyncio.sleep(60)
    ...     await client.disconnect()
    >>>
    >>> asyncio.run(main())
"""

from ._book import OddsBook, OddsContext
from ._entities import (
    AmericanFootballHandicap,
    AmericanFootballMatch,
    AmericanFootballMoneyline,
    AmericanFootballTotal,
    BaseballHandicap,
    BaseballMatch,
    BaseballMoneyline,
    BaseballTotal,
    BasketballHandicap,
    BasketballMatch,
    BasketballMoneyline,
    BasketballPlayerPropOverUnder,
    BasketballTotal,
    BoxingFight,
    BoxingMoneyline,
    CricketMatch,
    CricketMoneyline,
    FootballHandicap,
    FootballMatch,
    FootballMoneyline,
    FootballTotal,
    HandballHandicap,
    HandballMatch,
    HandballMoneyline,
    HandballTotal,
    HockeyHandicap,
    HockeyMatch,
    HockeyMoneyline,
    HockeyRegulationMoneyline,
    HockeyTotal,
    Level,
    Market,
    MmaFight,
    MmaMoneyline,
    OrderBook,
    Quote,
    RugbyLeagueHandicap,
    RugbyLeagueMatch,
    RugbyLeagueMoneyline,
    RugbyLeagueTotal,
    Selection,
    SportEvent,
    TennisHandicap,
    TennisMatch,
    TennisMoneyline,
    TennisTotal,
    UnknownMarket,
    UnknownSportEvent,
)
from ._gateway import ReconnectPolicy
from ._types import (
    AmericanFootballPeriod,
    BaseballPeriod,
    BasketballPeriod,
    BasketballTotalScope,
    Bookmaker,
    Competition,
    FootballPeriod,
    HandballPeriod,
    HockeyPeriod,
    MarketId,
    MarketKind,
    MARKET_KINDS,
    PlayerPropType,
    RugbyLeaguePeriod,
    SelectionId,
    SelectionKind,
    SelectionResult,
    Sport,
    SportEventId,
    SportEventKind,
    SPORT_EVENT_KINDS,
    TennisPeriod,
    TennisTotalScope,
    TennisUnit,
    TotalScope,
)
from .client import (
    Client,
    ConnectionState,
    ConnectionStatus,
    DisconnectedEvent,
    ErrorEvent,
    OddsChangedEvent,
    ReconnectingEvent,
    ResyncEvent,
    SourceClearedEvent,
    SportEventAddedEvent,
    SportEventRemovedEvent,
    SportEventUpdatedEvent,
    create_client,
)
from .id_helper import IdHelper

__version__ = "0.3.1"

__all__ = [
    # Client surface
    "Client",
    "ConnectionState",
    "ConnectionStatus",
    "DisconnectedEvent",
    "ErrorEvent",
    "IdHelper",
    "OddsBook",
    "OddsChangedEvent",
    "OddsContext",
    "ReconnectPolicy",
    "ReconnectingEvent",
    "ResyncEvent",
    "SourceClearedEvent",
    "SportEventAddedEvent",
    "SportEventRemovedEvent",
    "SportEventUpdatedEvent",
    "create_client",
    # Entities
    "AmericanFootballHandicap",
    "AmericanFootballMatch",
    "AmericanFootballMoneyline",
    "AmericanFootballTotal",
    "BaseballHandicap",
    "BaseballMatch",
    "BaseballMoneyline",
    "BaseballTotal",
    "BasketballHandicap",
    "BasketballMatch",
    "BasketballMoneyline",
    "BasketballPlayerPropOverUnder",
    "BasketballTotal",
    "BoxingFight",
    "BoxingMoneyline",
    "CricketMatch",
    "CricketMoneyline",
    "FootballHandicap",
    "FootballMatch",
    "FootballMoneyline",
    "FootballTotal",
    "HandballHandicap",
    "HandballMatch",
    "HandballMoneyline",
    "HandballTotal",
    "HockeyHandicap",
    "HockeyMatch",
    "HockeyMoneyline",
    "HockeyRegulationMoneyline",
    "HockeyTotal",
    "Level",
    "Market",
    "MmaFight",
    "MmaMoneyline",
    "OrderBook",
    "Quote",
    "RugbyLeagueHandicap",
    "RugbyLeagueMatch",
    "RugbyLeagueMoneyline",
    "RugbyLeagueTotal",
    "Selection",
    "SportEvent",
    "TennisHandicap",
    "TennisMatch",
    "TennisMoneyline",
    "TennisTotal",
    "UnknownMarket",
    "UnknownSportEvent",
    # Type aliases
    "AmericanFootballPeriod",
    "BaseballPeriod",
    "BasketballPeriod",
    "BasketballTotalScope",
    "Bookmaker",
    "Competition",
    "FootballPeriod",
    "HandballPeriod",
    "HockeyPeriod",
    "MARKET_KINDS",
    "MarketId",
    "MarketKind",
    "PlayerPropType",
    "RugbyLeaguePeriod",
    "SelectionId",
    "SelectionKind",
    "SelectionResult",
    "Sport",
    "SPORT_EVENT_KINDS",
    "SportEventId",
    "SportEventKind",
    "TennisPeriod",
    "TennisTotalScope",
    "TennisUnit",
    "TotalScope",
    # Version
    "__version__",
]
